[package]
name = "rs-shell-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
rs-shell-core   = { path = "../rs-shell-core" }
rs-shell-config = { path = "../rs-shell-config" }
gtk4            = { workspace = true }
glib            = { workspace = true }
freedesktop-desktop-entry = { workspace = true }
serde           = { workspace = true }
anyhow          = { workspace = true }
tracing         = { workspace = true }
tokio           = { workspace = true }

[dev-dependencies]
tempfile = "3"
