name: CI

on:
  push:
    branches:
      - trunk
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build workspace
        run: cargo build --workspace
      - name: Test workspace
        run: cargo test --workspace
      - name: Clippy workspace
        run: cargo clippy --workspace -- -D warnings
      - name: Check formatting
        run: cargo fmt --check
